mod crypto;
mod models;

use arc_swap::ArcSwap;
use futures::StreamExt;
use notify::{Config, RecommendedWatcher, RecursiveMode, Watcher};
use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Stdio;
use std::sync::{Arc, Mutex};
use tokio::io::AsyncWriteExt;
use tokio::process::Command;
use tokio_util::codec::{FramedRead, LinesCodec};

const MAX_JSON_RPC_LINE_BYTES: usize = 1024 * 1024 * 10;

/// Loads and parses the RiskGate policy constraints from the control plane, returning a default strict-block on failure.
fn load_policy(path: &str) -> models::GateConfig {
    if let Ok(content) = fs::read_to_string(path) {
        // Attempt to parse out the fields generated by our control plane
        if let Ok(val) = serde_json::from_str::<models::GateConfig>(&content) {
            return val;
        }
    }
    // Default fallback if parsing fails or file doesn't exist
    models::GateConfig {
        agent_id: "default".to_string(),
        authorized_targets: vec!["*".to_string()],
        allowed_actions: Vec::new(),
        forbidden_actions: Vec::new(),
        evidence_ttl_seconds: 60,
        require_receipt: true,
        public_key_b64: None,
    }
}

/// Entry point for the RiskGate Stdio Broker. Initializes causal observability, sets up lock-free RCU policy hot-reloading, 
/// and spawns the secure execution wrapper for the target actuator binary.
#[tokio::main]
async fn main() {
    // GENERATION 7: Initialize Unified Causal Observability (OpenTelemetry foundation)
    // We emit structured logs that can be captured by an OTel collector (e.g. Jaeger)
    tracing_subscriber::fmt()
        .with_max_level(tracing::Level::INFO)
        .with_writer(std::io::stderr) // Output to stderr to not pollute the MCP JSON-RPC stdout
        .init();

    tracing::info!("Initializing RiskGate Stdio Broker (Unified Causal Observability Active)");

    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: mcp_stdio_broker <target_command> [args...]");
        std::process::exit(1);
    }

    let target_cmd = &args[1];
    let target_args = &args[2..];

    // Idempotency Cache to prevent Short-Window Replay Attacks
    let nonce_cache: Arc<Mutex<BTreeMap<i64, Vec<String>>>> = Arc::new(Mutex::new(BTreeMap::new()));

    // RCU Epochs (Lock-Free Hot Reloading)
    // The policy is stored in an ArcSwap, allowing the worker threads to pull
    // lock-free snapshots of the config in microseconds.
    let policy_path = env::var("RGE_BROKER_POLICY_PATH")
        .unwrap_or_else(|_| "../control_plane/out/github-mcp-agent_riskgate.json".to_string());
    let initial_config = load_policy(&policy_path);
    let rcu_config = Arc::new(ArcSwap::from_pointee(initial_config));
    let rcu_config_clone = rcu_config.clone();
    let policy_path_for_watcher = policy_path.clone();
    let watch_path = PathBuf::from(&policy_path)
        .parent()
        .map(Path::to_path_buf)
        .unwrap_or_else(|| PathBuf::from("."));

    // Spawn a background blocking thread for the synchronous notify watcher
    tokio::task::spawn_blocking(move || {
        let (tx, rx) = std::sync::mpsc::channel();
        let mut watcher = RecommendedWatcher::new(tx, Config::default()).unwrap();

        if watch_path.exists() {
            watcher
                .watch(&watch_path, RecursiveMode::NonRecursive)
                .unwrap();
        }

        for res in rx {
            match res {
                Ok(event) => {
                    // Only trigger if our config file or the k8s symlink is modified
                    if format!("{:?}", event).contains("riskgate.json")
                        || format!("{:?}", event).contains("..data")
                    {
                        let new_config = load_policy(&policy_path_for_watcher);
                        rcu_config_clone.store(Arc::new(new_config));
                        eprintln!("[Control Plane] RCU Epoch Advanced! Hot-reloaded Zero-Trust constraints lock-free.");
                    }
                }
                Err(e) => eprintln!("watch error: {:?}", e),
            }
        }
    });

    let mut command = Command::new(target_cmd);
    command
        .env_clear() // Elite Security: Scrub environment variables to prevent credential leaks to the untrusted LLM actuator
        .env("PATH", env::var("PATH").unwrap_or_default()) // Only pass explicit safe variables
        .args(target_args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::inherit())
        .kill_on_drop(true); // Elite Security: Prevent Zombie/Orphan Actuator Process Leak

    unsafe {
        command.pre_exec(|| {
            // Elite Security: Air-Gapped execution (NEWNET) + IPC/UTS isolation
            let flags = libc::CLONE_NEWIPC | libc::CLONE_NEWUTS | libc::CLONE_NEWNET;
            if libc::unshare(flags) != 0 {
                eprintln!("CRITICAL WARNING: Could not unshare namespaces (Requires CAP_SYS_ADMIN). In production, this MUST abort to prevent Fail-Open execution. Proceeding for local demo only.");
            }

            // Elite Security: Kernel-level Zombie process prevention (Pacto de Suicidio)
            libc::prctl(libc::PR_SET_PDEATHSIG, libc::SIGKILL);

            // Elite Security: Fork Bomb and Memory Exhaustion Prevention
            let rlimit_nproc = libc::rlimit {
                rlim_cur: 100, // Max processes
                rlim_max: 100,
            };
            libc::setrlimit(libc::RLIMIT_NPROC, &rlimit_nproc);

            let rlimit_as = libc::rlimit {
                rlim_cur: 1024 * 1024 * 1024 * 2, // 2GB memory limit
                rlim_max: 1024 * 1024 * 1024 * 2,
            };
            libc::setrlimit(libc::RLIMIT_AS, &rlimit_as);
            
            // Elite PrivEsc Prevention: Drop root privileges before exec if running as root.
            if libc::geteuid() == 0 {
                // In production, fetch UID/GID from config. Using 1000 as standard unprivileged user.
                let target_uid = std::env::var("RGE_CHILD_UID").unwrap_or_else(|_| "1000".to_string()).parse::<u32>().unwrap_or(1000);
                let target_gid = std::env::var("RGE_CHILD_GID").unwrap_or_else(|_| "1000".to_string()).parse::<u32>().unwrap_or(1000);
                
                if libc::setgid(target_gid) != 0 || libc::setuid(target_uid) != 0 {
                    eprintln!("CRITICAL: Failed to drop root privileges. Aborting child execution to prevent Privilege Escalation.");
                    std::process::exit(1);
                }
            }
            Ok(())
        });
    }

    let mut child = command.spawn().expect("Failed to spawn child process");

    let mut child_stdin = child.stdin.take().expect("Failed to open child stdin");
    let child_stdout = child.stdout.take().expect("Failed to open child stdout");

    let stdout_task = tokio::spawn(async move {
        let codec = LinesCodec::new_with_max_length(MAX_JSON_RPC_LINE_BYTES);
        let mut framed_stdout = FramedRead::new(child_stdout, codec);
        let mut stdout = tokio::io::stdout();
        while let Some(res) = framed_stdout.next().await {
            match res {
                Ok(line) => {
                    let out_str = format!("{}\n", line);
                    if let Err(e) = stdout.write_all(out_str.as_bytes()).await {
                        tracing::warn!("Failed to write to stdout: {}", e);
                        break;
                    }
                    if let Err(e) = stdout.flush().await {
                        tracing::warn!("Failed to flush stdout: {}", e);
                        break;
                    }
                }
                Err(e) => {
                    tracing::warn!("Child stdout exceeded broker frame limit: {}", e);
                    break;
                }
            }
        }
    });

    let nonce_cache_clone = nonce_cache.clone();
    let stdin_task = tokio::spawn(async move {
        let stdin = tokio::io::stdin();
        let codec = LinesCodec::new_with_max_length(MAX_JSON_RPC_LINE_BYTES);
        let mut framed_stdin = FramedRead::new(stdin, codec);

        let mut stdout_err = tokio::io::stdout();

        while let Some(res) = framed_stdin.next().await {
            match res {
                Ok(line_content) => {
                    let line = format!("{}\n", line_content);

                    if let Ok(req) = serde_json::from_str::<models::JsonRpcRequest>(&line) {
                        if req.method == "tools/call" {
                            let mut allow = false;
                            let mut err_code = -32000;
                            let mut error_msg =
                                "RiskGate Blocked: Missing _receipt in params".to_string();
                            let current_config = rcu_config.load();

                            if let Some(params) = &req.params {
                                if let Some(receipt) = &params._receipt {
                                    // Causal Observability Trace Log
                                    // We emit structured logs linking the LLM intent ID to the kernel enforcement
                                    tracing::info!(intent_id = %receipt.intent_id, tool = %params.name, "Verifying cryptographic receipt for tool");

                                    // Clone data for the blocking thread to prevent CPU Starvation on the async executor
                                    let receipt_clone = receipt.clone();
                                    let name_clone = params.name.clone();
                                    let args_clone = params.arguments.clone();
                                    let config_clone = current_config.clone();
                                    
                                    // Idempotency Check & Optimistic Lock (TOCTOU Prevention)
                                    let mut is_replay = false;
                                    {
                                        let mut cache = nonce_cache_clone.lock().unwrap();
                                        if cache.values().any(|v| v.contains(&receipt_clone.intent_id)) {
                                            is_replay = true;
                                        } else {
                                            // Optimistically reserve the intent_id to prevent concurrent replays
                                            cache.entry(receipt_clone.timestamp).or_insert_with(Vec::new).push(receipt_clone.intent_id.clone());
                                        }
                                    }

                                    if is_replay {
                                        tracing::warn!(intent_id = %receipt_clone.intent_id, "Verification BLOCKED: Concurrent Replay Attack Detected");
                                        error_msg = format!("RiskGate Blocked: Replay Attack Detected (intent_id {} already executing or executed)", receipt_clone.intent_id);
                                    } else {
                                        // Offload heavy cryptographic signature verification to a blocking thread pool
                                        let decision = tokio::task::spawn_blocking(move || {
                                            crypto::verify_receipt(&receipt_clone, &name_clone, &args_clone, &config_clone)
                                        }).await.unwrap_or_else(|_| crypto::GateDecision::Block("Internal Crypto Thread Panic".to_string()));

                                        match decision {
                                            crypto::GateDecision::Allow => {
                                                tracing::info!(intent_id = %receipt.intent_id, "Verification SUCCESS. RiskGate Approved.");
                                                
                                                let mut cache = nonce_cache_clone.lock().unwrap();
                                                // Deterministically prune expired nonces (O(log N))
                                                let expire_time = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap().as_secs() as i64 - current_config.evidence_ttl_seconds;
                                                cache.retain(|&ts, _| ts >= expire_time);
                                                
                                                allow = true;
                                            }
                                            crypto::GateDecision::Block(reason) => {
                                                // Rollback optimistic lock
                                                {
                                                    let mut cache = nonce_cache_clone.lock().unwrap();
                                                    if let Some(vec) = cache.get_mut(&receipt.timestamp) {
                                                        vec.retain(|id| id != &receipt.intent_id);
                                                    }
                                                }
                                                tracing::warn!(intent_id = %receipt.intent_id, "Verification BLOCKED: {}", reason);
                                                error_msg = format!("RiskGate Blocked: {}", reason);
                                            }
                                            crypto::GateDecision::Suspend(reason) => {
                                                // Rollback optimistic lock
                                                {
                                                    let mut cache = nonce_cache_clone.lock().unwrap();
                                                    if let Some(vec) = cache.get_mut(&receipt.timestamp) {
                                                        vec.retain(|id| id != &receipt.intent_id);
                                                    }
                                                }
                                                tracing::warn!(intent_id = %receipt.intent_id, "Verification SUSPENDED: {}", reason);
                                                err_code = -32001;
                                                error_msg = format!("RiskGate Suspended: {}", reason);
                                            }
                                        }
                                    }
                                } else if !current_config.require_receipt {
                                    allow = true;
                                }
                            } else if !current_config.require_receipt {
                                allow = true;
                            }

                            if !allow {
                                let err_res = models::JsonRpcResponse {
                                    jsonrpc: "2.0".to_string(),
                                    id: req.id,
                                    error: models::JsonRpcError {
                                        code: err_code,
                                        message: error_msg,
                                    },
                                };
                                let err_json = serde_json::to_string(&err_res).unwrap_or_else(|_| "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"Internal JSON error\"}}".to_string());
                                if let Err(e) = stdout_err.write_all(format!("{}\n", err_json).as_bytes()).await {
                                    tracing::error!("Failed to write error to stdout: {}", e);
                                    break;
                                }
                                if let Err(e) = stdout_err.flush().await {
                                    tracing::error!("Failed to flush error to stdout: {}", e);
                                    break;
                                }
                                continue;
                            }
                        }
                    }

                    if let Err(e) = child_stdin.write_all(line.as_bytes()).await {
                        tracing::error!("Failed to write to child stdin: {}", e);
                        break;
                    }
                    if let Err(e) = child_stdin.flush().await {
                        tracing::error!("Failed to flush child stdin: {}", e);
                        break;
                    }
                }
                Err(e) => {
                    let err_res = models::JsonRpcResponse {
                        jsonrpc: "2.0".to_string(),
                        id: serde_json::Value::Null,
                        error: models::JsonRpcError {
                            code: -32600,
                            message: format!("Broker IO Error or Payload Too Large: {}", e),
                        },
                    };
                    let err_json = serde_json::to_string(&err_res).unwrap_or_else(|_| "{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32603,\"message\":\"Internal JSON error\"}}".to_string());
                    let _ = stdout_err.write_all(format!("{}\n", err_json).as_bytes()).await;
                    let _ = stdout_err.flush().await;
                    break;
                }
            }
        }
    });

    let _ = child.wait().await;
    stdout_task.abort();
    stdin_task.abort();
}
